# Generated by Django 5.2.4 on 2025-08-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='base_price',
        ),
    ]
