# Generated by Django 5.2.4 on 2025-07-30 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
