# Generated by Django 5.2.7 on 2025-10-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderItem', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
